[package]
name = "dpapi-fuzzing"
version = "0.1.0"
edition = "2024"

[dependencies]
dpapi-pdu = { workspace = true, features = ["arbitrary"] }
dpapi-core = { workspace = true, features = [] }
arbitrary = { version = "1", features = ["derive"] }
pretty_assertions = "1.4"
